### ISSUE TITLE
Separate rendering for two screens

### ISSUE THREAD

**Issue by qian256** [dngoins/HololensDXTutorials#4]
Hi,
Thanks for sharing the great work! I tracked to this repository from some threads in Windows Holographic forum, about the separate rendering for two screens of HoloLens. Do you still have some code demonstrating the "issue" of separate rendering? I would like to re-create that effect.

**Comment by dngoins** [comment]
Yes actually look at the shader logic inside of the DirectXTK (git@github.com:dngoins/DirectXTK.git)
https://github.com/dngoins/DirectXTK/commit/e6c6801c79ca14707831320dd771efb77bcd3dcb 

The above commit has what's needed to take a shader which does not render properly on both eyes. Looking into that logic allows you to undo it and figure out how to render different content in different screens. Basically just render different content into the different buffers
